#include "timer.h"

void Timer_Init(void){
	SIM->SCGC6 |= SIM_SCGC6_PIT_MASK;
	PIT->MCR = 0x00U;
	PIT->CHANNEL[0].LDVAL = 0x00d551f3U;
	PIT->CHANNEL[0].TCTRL = 0x00U;
	PIT->CHANNEL[0].TFLG = PIT_TFLG_TIF_MASK;
	
	NVIC_SetPriority(22,2);
	NVIC_EnableIRQ(22);
	
	PIT->CHANNEL[0].TCTRL = (PIT_TCTRL_TIE_MASK|PIT_TCTRL_TEN_MASK);
	
	PIT->CHANNEL[1].LDVAL = 0x006aa8afU;
	PIT->CHANNEL[1].TCTRL = 0x00U;
	PIT->CHANNEL[1].TFLG = PIT_TFLG_TIF_MASK;
	
	PIT->CHANNEL[1].TCTRL = (PIT_TCTRL_TIE_MASK|PIT_TCTRL_TEN_MASK);
}